name: Validate

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate
    strategy:
      matrix:
        include:
          - os: macos-latest
            command: ".github/workflows/val.sh"
          - os: ubuntu-latest
            command: ".github/workflows/val.sh"
            chmod: true
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
            submodules: recursive
    - if: matrix.os == 'macos-latest'
      name: Build
      run: |
        brew install automake
        INCLUDE_DIR="-I/opt/homebrew/opt/openssl@3/include/" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.4.0/lib" make all -j
        ls /usr/local/lib/
    - if: matrix.os == 'ubuntu-latest'
      name: Build
      run: make all -j
    - name: Validate
      run: |
        export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$(pwd)/htslib/"
        echo "this is library path: $LD_LIBRARY_PATH"
        chmod +x .github/workflows/val.sh
        ${{ matrix.command }}

